apiVersion: v1
kind: Template
metadata:
  name: pathfinder-template
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"app"}}'
    labels:
      app: pathfinder-ui
      application: pathfinder-ui
      bundle: pathfinder
    name: pathfinder
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/port: "8080"
      prometheus.io/scheme: http
      prometheus.io/scrape: "true"
    creationTimestamp: null
    labels:
      app: pathfinder-server
      bundle: pathfinder
    name: pathfinder-server
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /management/health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1  
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /management/health
        port: 8080
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1  
    selector:
      app: pathfinder-server
      deploymentconfig: pathfinder-server
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    creationTimestamp: null
    generation: 1
    labels:
      app: pathfinder-server
      bundle: pathfinder
    name: pathfinder-server
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: quay.io/pathfinder/pathfinder-server
      generation: null
      importPolicy:
        scheduled: true
      name: latest
      referencePolicy:
        type: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    creationTimestamp: null
    generation: 1
    labels:
      app: pathfinder-ui
      bundle: pathfinder
    name: pathfinder-ui
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: quay.io/pathfinder/pathfinder-ui
      generation: null
      importPolicy:
        scheduled: true
      name: latest
      referencePolicy:
        type: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
    creationTimestamp: null
    generation: 1
    labels:
      app: pathfinder-server
      bundle: pathfinder
    name: pathfinder-server
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: pathfinder-server
      deploymentconfig: pathfinder-server
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
        creationTimestamp: null
        labels:
          app: pathfinder-server
          deploymentconfig: pathfinder-server
          bundle: pathfinder
      spec:
        containers:
        - env:
          - name: JAVA_OPTIONS
            value: -Xmx1024m -Dspring.cloud.kubernetes.secrets.enableApi=false -Dspring.profiles.active=swagger,prodose
              -Dspring.cloud.kubernetes.secrets.name=mongodb -Dspring.cloud.kubernetes.secrets.paths=/tmp/secrets
          - name: JAVA_ENABLE_DEBUG
            value: "false"
          image: 172.30.1.1:5000/pathfinder/pathfinder-server:latest
          imagePullPolicy: Always
          name: pathfinder-server
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /management/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /management/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 700Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /tmp/secrets/mongodb
            name: mongodb-secret
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccountName: pathfinder        
        terminationGracePeriodSeconds: 30
        volumes:
        - name: mongodb-secret
          secret:
            defaultMode: 420
            secretName: mongodb
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - pathfinder-server
        from:
          kind: ImageStreamTag
          name: pathfinder-server:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: pathfinder-tls    
      description: The oauth proxy's target port
    creationTimestamp: null
    labels:
      app: pathfinder-ui
      application: pathfinder-ui
      bundle: pathfinder
    name: pathfinder-ui
  spec:
    ports:
    - name: proxy
      port: 443
      targetPort: 8443
    selector:
      deploymentConfig: pathfinder-ui
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      description: Route for application's http service.
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: pathfinder-ui
      application: pathfinder-ui
      bundle: pathfinder
    name: app
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: Reencrypt
    to:
      kind: Service
      name: pathfinder-ui
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: pathfinder-ui
      application: pathfinder-ui
      bundle: pathfinder
    name: pathfinder-ui
  spec:
    replicas: 1
    selector:
      deploymentConfig: pathfinder-ui
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: pathfinder-ui
          application: pathfinder-ui
          deploymentConfig: pathfinder-ui
          bundle: pathfinder
        name: pathfinder-ui
      spec:
        containers:
        - args:
          - --https-address=:8443
          - --provider=openshift
          - --openshift-service-account=pathfinder
          - --upstream=http://localhost:8080
          - --tls-cert=/etc/tls/private/tls.crt
          - --tls-key=/etc/tls/private/tls.key
          - --cookie-secret=SECRET
          - --skip-auth-regex=/api/*
          # image: registry.redhat.io/openshift4/ose-oauth-proxy:latest
          image: registry.redhat.io/openshift3/oauth-proxy:latest
          imagePullPolicy: IfNotPresent
          name: oauth-proxy
          ports:
          - containerPort: 8443
            name: public
          volumeMounts:
          - mountPath: /etc/tls/private
            name: pathfinder-tls          
        - env:
          - name: JWS_ADMIN_USERNAME
            value: VnTsjJjY
          - name: JWS_ADMIN_PASSWORD
            value: xfnfyTKW
          - name: PATHFINDER_SERVER
            value: http://pathfinder-server:8080
          - name: PATHFINDER_SELF
            value: .
          image: 172.30.1.1:5000/pathfinder/pathfinder-ui:latest
          imagePullPolicy: Always
          name: pathfinder-ui
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - curl --noproxy '*' -s -u VnTsjJjY:xfnfyTKW 'http://localhost:8080/manager/jmxproxy/?get=Catalina%3Atype%3DServer&att=stateName'
                |grep -iq 'stateName *= *STARTED'
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccountName: pathfinder        
        terminationGracePeriodSeconds: 60
        volumes:
        - name: pathfinder-tls
          secret:
            secretName: pathfinder-tls        
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - pathfinder-ui
        from:
          kind: ImageStreamTag
          name: pathfinder-ui:latest
      type: ImageChange
    - type: ConfigChange
  